UnsetSentinel = object()

# Time
ONE_DAY_IN_SECONDS = 60 * 60 * 24

# Game rules
NUM_PROMPTS_IN_CATEGORY = 3
MIN_CATEGORIES_IN_LOBBY = 3
MAX_CATEGORIES_IN_LOBBY = 5
MIN_NUM_PLAYERS = 2
MAX_NUM_PLAYERS = 8
